name: ZAP Scan
on:
  workflow_run:
    workflows: ['Build and Deploy']
    types: [completed]

jobs:
  baseline-scan:
    name: Baseline Scan
    runs-on: ubuntu-latest
    environment: Dokku
    steps:
    - name: Wait until Dokku replaces the app version
      run: sleep 60s
      shell: bash

    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'http://${{ secrets.DOKKU_APPNAME }}.${{ secrets.DOKKU_HOSTNAME }}/'
